<?php

/**
 * Override Class
 * @category    Clever
 * @package     Clever_Adwords
 * @author      Hector Luis Barrientos <ticaje@filetea.me>
 */
class Clever_Adwords_Override_Block_Widget_Form extends Mage_Adminhtml_Block_Widget_Form
{
    protected $_helper;
    protected function _construct()
    {
        $this->_helper = Mage::helper('clever_adwords');
        parent::_construct(); // TODO: Change the autogenerated stub
    }

    protected function register($registry)
    {
        if (Mage::registry($registry)) {
            $_data = Mage::registry($registry)->getData();
        } else {
            $_data = array();
        }
        return $_data;
    }
}