<?php

// autoload.php @generated by Composer

if (!class_exists(ComposerAutoloaderInit8f86d9199a2fccc1538295ae6c7f0779)){
    require_once __DIR__ . '/composer/autoload_real.php';
    return ComposerAutoloaderInit8f86d9199a2fccc1538295ae6c7f0779::getLoader();
}
